name: Update dependencies

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Checkout the depot tools they are needed by roll_deps.sh

      - name: Checkout depot tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Update PATH
        run: echo "./depot_tools" >> $GITHUB_PATH

      - name: Download dependencies
        run: python3 utils/git-sync-deps

      - name: Setup git user information
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b roll_deps

      - name: Update dependencies
        run: |
          utils/roll_deps.sh
     
      - name: Check for new commits

      - name: Push changes and create PR
        run: |
          git push --force --set-upstream origin roll_deps
          gh pr create --base main -f -r s-perron
        env:
          GITHUB_TOKEN: ${{ github.token }}
